version: '3.9'

services:
  db:
    image: postgres:12-alpine
    container_name: some-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  pgdata:
